config/routes.rb
Rails.application.routes.draw do
  root 'cats#new'

  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'sessions/create'
  delete 'sign-out', to: 'sessions#destroy', as: :sign_out

  get 'cats', to: 'cats#index', as: :cats
  get '/:giphy_id', to: 'cats#show', as: :cat
  post '/:giphy_id', to: 'cats#create'
  delete '/:giphy_id', to: 'cats#destroy'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :likes
  has_many :users, through: :likes

  attr_reader :gif, :tweet

  validates :giphy_id, presence: true, uniqueness: true

  after_find :giphy_sync
  after_initialize :build_tweet

  def self.from_giphy(giphy_id: nil, tag: 'cat')
    gif = giphy_id ? Giphy.by_id(giphy_id) : Giphy.random(tag: tag)
    new(gif: gif, giphy_id: gif.id)
  end

  def self.from_giphy_translate(phrase)
    gif = Giphy.translate(phrase)
    new(gif: gif, giphy_id: gif.id)
  end

  def gif=(gif)
    @gif = gif
  end

  private

  def build_tweet
    @tweet = TweetLink.new(self.giphy_id)
  end

  def giphy_sync
    @gif = Giphy.by_id(giphy_id)
  end
end

app/models/concerns/cat_fact.rb
class CatFact
  BASE_URL = 'http://catfacts-api.appspot.com/api/facts?number='

  attr_reader :facts

  def self.get(number = 1)
    return new.facts.first unless number > 1
    new(number).facts
  end

  def initialize(number = 1)
    @facts = request("#{BASE_URL}#{number}")['facts']
  end

  private

  def request(url)
    open_uri = open(url)
    json = JSON.load(open_uri)
  end
end

app/models/concerns/giphy.rb
class Giphy
  BASE_URL = 'http://api.giphy.com/v1/gifs/'
  API_KEY  = ENV["GIPHY_API_KEY"]

  def self.search(query, options = { limit: nil, offset: nil, rating: 'y,g', fmt: nil })
    params = build_params(options.merge(q: query))
    url = BASE_URL + 'search?' + params
    Giphy::Response.parse(request(url))
  end

  def self.by_id(id)
    params = build_params
    url = BASE_URL + "#{id}?" + params
    Giphy::Response.parse(request(url))
  end

  def self.by_ids(*ids)
    params = build_params({ ids: ids.join(',') })
    url = BASE_URL.sub(/\/$/, '?') + params
    Giphy::Response.parse(request(url))
  end

  def self.translate(phrase, options = { rating: 'y,g', fmt: nil })
    params = build_params(options.merge(s: URI.encode(phrase)))
    url = BASE_URL + 'translate?' + params
    Giphy::Response.parse(request(url))
  end

  def self.random(options = { tag: nil, rating: 'y,g', fmt: nil })
    params = build_params(options)
    url = BASE_URL + 'random?' + params
    Giphy::Response.parse(request(url))
  end

  # def self.trending
  # end

  class << self
    private

    def request(url)
      open_uri = open(url)
      JSON.load(open_uri)["data"]
    end

    def build_params(params = {})
      params.delete_if { |k, v| v.nil? }
      params.merge(api_key: API_KEY).map { |k, v| "#{k}=#{v}" }.join('&')
    end
  end
end

app/models/concerns/giphy/gif.rb
module Giphy
  class Gif
    attr_reader :id, :images, :rating

    def self.new_collection(collection)
      collection.map { |obj| new(obj) }
    end

    def initialize(data = {})
      data.each { |k, v| instance_variable_set("@#{k}", v) }
      open_structize_images
    end

    def url
      images.fixed_width.url
    end

    private

    def open_structize_images
      @images.each { |k, v| @images[k] = OpenStruct.new(v) }
      @images = OpenStruct.new(@images)
    end
  end
end

app/models/concerns/giphy/response.rb
class Giphy
  class Response
    IMAGE_SIZE = 'original'
    attr_reader :id, :images, :rating

    def self.parse(data)
      if data.empty?
        nil
      elsif data.is_a? Array
        data.map { |obj| new(obj) }
      else
        new(data)
      end
    end

    def initialize(data = {})
      data.each { |k, v| instance_variable_set("@#{k}", v) }
      open_structize_images if images
    end

    def url
      if images
        images.send(IMAGE_SIZE).url
      else
        @image_url
      end
    end

    private

    def open_structize_images
      @images.each { |k, v| @images[k] = OpenStruct.new(v) }
      @images = OpenStruct.new(@images)
    end
  end
end

app/models/concerns/tweet_link.rb
class TweetLink
  BASE_URL = 'https://twitter.com/intent/tweet?'

  def initialize(giphy_id)
    @giphy_id = giphy_id
  end

  def to_s
    BASE_URL + build_params
  end

  private

  attr_reader :giphy_id

  def build_params
    params.map { |k, v| "#{k}=#{v}" }.join('&')
  end

  def params
    {
      text: 'LOOK AT DIS KITTEH, U MITE LIEK IT?',
      url: "#{ENV["URL"]}#{giphy_id}",
      hashtags: 'werzukittehz'
    }
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :cat
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :cats, through: :likes

  def self.from_oauth(auth)
    find_by(auth.slice('provider', 'uid')) || create_from_oauth(auth)
  end

  def self.create_from_oauth(auth)
    create do |user|
      user.provider = auth['provider']
      user.uid      = auth['uid']
      user.name     = auth['info']['name']
      user.nickname = auth['info']['nickname']
      user.image    = auth['info']['image']
    end
  end

  def cats_include?(cat)
    cats.map(&:giphy_id).include? cat.giphy_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :init_focus

  private

  def user_signed_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if !user_signed_in? && params[:cat]
      session[:tmp_cat_params] = cat_params
      redirect_to '/auth/twitter'
    elsif !user_signed_in?
      render 'shared/sign_in_alert'
    end
  end

  def init_focus
    if request.env["HTTP_ACCEPT"].include? 'html'
      session[:focus] = ENV['FOCUS']
    else
      session[:focus] ||= ENV['FOCUS']
    end
  end

  def set_focus(focus)
    session[:focus] = focus
  end

  def reset_focus
    session[:focus] = ENV['FOCUS']
  end

  def current_focus
    session[:focus]
  end

  helper_method :current_user, :user_signed_in?, :current_focus
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :reset_focus, only: :index
  before_action :set_cat, only: :destroy
  before_action :find_or_initialize, only: :create
  before_filter :authenticate_user!, only: [:create, :index]

  def index
    @cats = current_user.cats
  end

  def new
    @cat = Cat.from_giphy(tag: current_focus)
  rescue
    reset_focus
    @cat = Cat.from_giphy
  end

  def create
    current_user.cats << @cat
    @cat.save
  end

  def show
    @cat = Cat.from_giphy(giphy_id: query_param)
  rescue
    easter_egg
  end

  def destroy
    current_user.cats.delete(@cat)
  end

  private

  def set_cat
    @cat = Cat.find_by(giphy_id: params[:giphy_id])
  end

  def find_or_initialize
    @cat = Cat.find_by(giphy_id: params[:giphy_id])
    @cat = Cat.from_giphy(giphy_id: params[:giphy_id]) unless @cat
  end

  def cat_params
    params.require(:cat).permit(:giphy_id)
  end

  def query_param
    params[:giphy_id]
  end

  def easter_egg
    flash.now[:notice] = "U can has #{query_param}!"
    set_focus(query_param)
    @cat = Cat.from_giphy_translate(query_param)
  rescue
    no_easter_egg
  end

  def no_easter_egg
    reset_focus
    flash.now[:notice] = "U cant has #{query_param}."
    @cat = Cat.from_giphy_translate('not found!')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_oauth(ENV['omniauth.auth'])
    session[:user_id] = user.id

    if session[:tmp_cat_params]
      set_cat
      redirect_to_create_cat
    else
      redirect_to root_path, notice: "Hay. Welcom 2 teh kats."
    end
  end

  def destroy
    session[:user_id] = nil
    session[:focus] = nil
    redirect_to root_path, notice: "K Bai."
  end

  private

  def redirect_to_create_cat
    current_user.cats << @cat

    if @cat.save
      redirect_to cat_path(@cat.giphy_id), notice: "Hay. Welcom 2 teh kats."
    else
      redirect_to cat_path(@cat.giphy_id), alert: "Didn't save it."
    end
  end

  def set_cat
    @cat = Cat.find_by(session[:tmp_cat_params])
    @cat = Cat.new(session[:tmp_cat_params]) unless @cat
    session[:tmp_cat_params] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<div class="text-center">
  <div class="row">
    <%= render partial: 'cat_gif', locals: { cat: cat } %>
  </div>
  <div class="row">
    <div class="col-sm-4 actions pull-left">
      <%= render 'like' %>
    </div>
    <div class="col-sm-4 actions pull-right">
      <%= render 'moar' %>
    </div>
  </div>
</div>

app/views/cats/_cat_gif.html.erb
<%= link_to cat_path(cat.giphy_id), id: 'cat' do %>
  <%= image_tag cat.gif.url, class: 'img-responsive img-rounded center-block gif' %>
<% end %>

app/views/cats/_fact.html.erb
<a href="">
  <%= fa_icon 'info-circle' %>
</a>
<p class="lead hidden">
  <%= CatFact.get %>
</p>

app/views/cats/_likable.html.erb
<%= link_to cat_path(@cat.giphy_id), method: :post, id: 'likable', remote: true do %>
  <%= fa_stacked_icon "heart-o inverse", base: "circle", class: "fa-3x" %>
<% end %>

app/views/cats/_like.html.erb
<div class="like">
  <% if user_signed_in? && current_user.cats_include?(@cat) %>
    <%= render 'unlikable' %>
  <% else %>
    <%= render 'likable' %>
  <% end %>
</div>

app/views/cats/_moar.html.erb
<%= link_to root_path, id: 'moar', remote: true do %>
  <%= fa_stacked_icon "chevron-right inverse", base: "circle", class: "fa-3x" %>
<% end %>

app/views/cats/_tweet.html.erb
<a class="twitter-share-button" href="<%= @cat.tweet %>" onclick="window.open(this.href, 'OMG KITTEH', 'width=500,height=250,centerscreen=true'); return false;">
  Tweet
  <%= fa_icon 'twitter' %>
</a>

app/views/cats/_unlikable.html.erb
<%= link_to cat_path(@cat.giphy_id), method: :delete, id: 'unlikable', remote: true do %>
  <%= fa_stacked_icon "heart inverse", base: "circle", class: "fa-3x" %>
<% end %>

app/views/cats/create.js.erb
$('#likable').replaceWith('<%= j render "unlikable" %>')

app/views/cats/destroy.js.erb
$('#unlikable').replaceWith('<%= j render "likable" %>')

app/views/cats/index.html.erb
<%= link_to 'Moar kittehs?!!?1!', root_path, class: 'moar' %>

<% @cats.each do |cat| %>
  <%= link_to cat_path(cat.giphy_id) do %>
    <img src="<%= cat.gif.url %>" id="<%= cat.giphy_id %>"  class="img-responsive img-rounded center-block gif collecshun"/>
  <% end %>
<% end %>

<%= link_to 'Moar kittehs?!!?1!', root_path, class: 'moar' %>

app/views/cats/new.html.erb
<%= render @cat %>

app/views/cats/new.js.erb
var newCat   = $('<%= j render partial: "cat_gif", locals: { cat: @cat } %>').hide();
slideReplace('#cat', newCat);

var newTitle = $('<%= j render "layouts/title" %>').hide();
if ($('#title').text() != newTitle.text()) slideReplace('#title', newTitle);

var newLike  = $('<%= j render "like" %>')
var newTweet = $('<%= j render "tweet" %>')
$('.like').replaceWith(newLike);
$('.twitter-share-button').replaceWith(newTweet);

app/views/cats/show.html.erb
<%= render @cat %>

app/views/layouts/_collecshun_or_signout.html.erb
<% if current_page?('/cats') %>
  <%= link_to sign_out_path, method: :delete do %>
    Sign out
    <img src="<%= current_user.image %>" alt="current_user.name" class="img-circle" />
  <% end %>
<% else %>
  <%= link_to cats_path, class: 'brown' do %>
    <%= current_user.nickname %>
    <img src="<%= current_user.image %>" alt="current_user.name" class="img-circle" />
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="text-center alert fade in" onclick="hideAlert()">
    <%= content_tag :div, msg, class: name %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    FOR NORAH LOU
    <%= link_to 'Love Dad', 'http://drewfrom.space', class: 'brown' %>
    <% unless current_page?('/cats') %>
    <div class="pull-right">
      <%= render 'cats/tweet' %>
    </div>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <nav>
    <ul class="nav nav-pills pull-right">
      <% if user_signed_in? %>
        <li role="presentation">
          <%= render 'layouts/collecshun_or_signout' %>
        </li>
      <% else %>
        <li role="presentation">
          <%= link_to '/auth/twitter' do %>
            Sign in <%= fa_icon 'twitter 2x' %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= render 'layouts/title' %>
  </nav>
</div>

app/views/layouts/_title.html.erb
<h3 class="text-muted" id="title">
  <a href="<%= ENV['URL'] %>">
    <% if current_focus == ENV['FOCUS'] %>
      WERZUKITTEHSDAD
    <% else %>
      WERZU<%= current_focus.gsub(/\W/, '') %>DAD
    <% end %>
  </a>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KITTEH</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>

    <%= render 'layouts/flash' %>

    <div class="jumbotron">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_sign_in_notice.html.erb
<div class="text-center alert fade in" onclick="hideAlert()">
    <div class="notice">
      U haz 2 sine in furst
      <%= fa_icon 'arrow-circle-up' %>
    </div>
</div>

app/views/shared/sign_in_alert.js.erb
var notice = $('<%= j render "shared/sign_in_notice" %>').hide()

if (!$('.alert').length) {
  $('.jumbotron').prepend(notice);
  $('.alert').slideDown()

  window.setTimeout(function(){
    hideAlert();
  }, 4000);
}